### ISSUE TITLE
The pen click coordinates wrongly map to some Qt window such as Kate

### ISSUE THREAD

**Issue by braindevices** [linuxwacom/xf86-input-wacom#115] opened 2020-04-23 18:52 UTC
Ubuntu 19.10, default Gnome theme (3.34.2). Nvidia driver (Driver Version: 440.82)
Open Kate application. Wacom Intuos3 6x8.

SUMMARY
Whenever, I open a file in projects and the porjects tag appears, the position of wacom tablet mouse click event start to have huge offset to the actual cursor position (about 1/3 to 1/2 of the screen size). Thus the buttons on the top is not clickable by wacom pen, click at the top line in the editor results in moving editing cursor to 10th line or more. This happens in both absolute or relative mode. But the normal mouse click is still working.

STEPS TO REPRODUCE
1. start kate and open any file not in a project, the cursor and click position are perfectly matched.
2. check plugin setting make sure all types of projects are checked. 
3. Open any file in a project. Then try to click button or select text.

OBSERVED RESULT
The wacom pen click position starts to have huge offset again cursor location.

EXPECTED RESULT
There should be no offset.

Linux/KDE Plasma: Ubuntu 19.10
KDE Plasma Version: 5.62.0
KDE Frameworks Version: 5.62.0-0ubuntu1
Qt Version: 5.12.4+dfsg-4ubuntu1.1

I also reported in [kate](https://bugs.kde.org/show_bug.cgi?id=420478).

**Comment by jigpu** [comment] 2020-04-23 20:13
Please see https://github.com/linuxwacom/xf86-input-wacom/issues/93 and the upstream issue at https://bugreports.qt.io/browse/QTBUG-77826. The issue is supposed to be fixed in Qt 5.14.1.

**Closed by jigpu** 2020-04-23 20:13 UTC
